version: '3.6'

services:

  pywb:
    build: .
    volumes:
      - .:/home/was/swap/current

  nginx:
    image: nginx
    ports:
      - 8080:80

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - pywb
