version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.3.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
      - test
jobs:
  test:
    executor: ruby-rails/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build . -t was-pywb
      - run:
          name: Run image
          command: docker run --name was-pywb -d was-pywb
      - run:
          name: Test
          command: docker exec was-pywb bundle exec rake
