version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.2.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
      - test
jobs:
  test:
    executor:
      name: ruby-rails/ruby
      ruby-tag: '3.2.2'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build . -t was-pywb
      - run:
          name: Run image
          command: docker run --name was-pywb -d was-pywb
      - run:
          name: Test
          command: docker exec was-pywb bundle exec rake
