version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.1.1
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
      - ruby-rails/test-gem:
          name: test
          before-test:
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Spin up containers and verify running
                command: |
                  docker-compose up -d --build
                  docker-compose ps
                  docker container run --network container:project_nginx_1 \
                    docker.io/jwilder/dockerize \
                    -wait http://localhost:8080 \
                    -wait-retry-interval 1s \
                    -timeout 60s
