#!/bin/bash

# This script is called by our weekly dependency update job in Jenkins, before updating Ruby and other deps
cd pywb/

# Without these ENV changes, python gets confused and tries to use latin1
# encodings which breaks the updates below
export LANG=en_US.UTF-8
export LC_COLLATE=C.UTF-8

pip3 install --user pipx > was-pywb.txt &&
    pipx install uv --force >> was-pywb.txt &&
    ~/.local/bin/uv lock --upgrade -q --no-progress --color never >> was-pywb.txt

retVal=$?

git add uv.lock &&
    git commit -m "Update Python dependencies"

if [ $retVal -ne 0 ]; then
    echo "ERROR UPDATING PYTHON (was-pywb)"
    cat was-pywb.txt
fi

cd ..
